apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-app.fullname" . }}-postgres
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "fastapi-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database